### ISSUE TITLE
CMHeadphoneMotionManager using

### ISSUE THREAD

**Issue by nickaroot** [Cecemel20/iOSHeadTrack#1]
Hey! I think you can use CMHeadphoneMotionManager to enhance tracking with AirPods Pro/Max
https://developer.apple.com/documentation/coremotion/cmheadphonemotionmanager

Unfortunately, I have no time to be involved in coding, but that's might be interesting feature
(Camera precise is poor, iPhone is weighty 😄)

**Comment by ce3c** [comment]
Hi Nick, I'll certainly look into it as using AirPods for tracking would be nice, but I don't think AirPods contain a magnetometer.. I'm not using the camera, I just updated the readme so you might want to take a look at it.

**Comment by nickaroot** [comment]
Good news! AirPods Pro/Max contains Accelerometer, there's demo:
https://github.com/warrenm/HeadphoneMotion

A long time ago this API was incomplete, but now it works :)

**Comment by ce3c** [comment]
I meant magnetometer (edited my comment), I don't think you can sense 'horizontal' rotation (looking left/right) with just an accelerometer. Also, I don't own AirPods Pro/Max so I can't test it but certainly willing to take a look at it if someone send me a pair 😉.

**Comment by nickaroot** [comment]
Hmm, I just record a demo-video :)

https://yadi.sk/i/vdBxDaKvpIcUlg

**Comment by ce3c** [comment]
Wow that's really cool. If I ever get AirPods Pro I'll certainly add that. (Got AirPods 2 now..)

Can you close this issue? I'll reopen it if I ever get my hands on some new AirPods.

**Comment by nickaroot** [comment]
Ok, I may have time to do it later

**Comment by ce3c** [comment]
Just letting you know that I got AirPods Pro so I'll be adding this feature soon.

**Comment by nickaroot** [comment]
That’s awesome
Happy New Year)

**Comment by ce3c** [comment]
I've done some initial testing, the latency is quite high compared to using the device's sensors. Also there doesn't seem to be a way to set the refresh rate for the CMHeadphoneMotionManager. I've measured the rate of incoming UDP packets using a python script and it seems to hover around 22-23Hz.

There's also going to have to be some way to play the computer's audio through the AirPods which won't be easy as they need to be connected to the iPhone.. I guess the easiest way would be to build in a [VBAN](https://vb-audio.com/Voicemeeter/VBANProtocol_Specifications.pdf) receiver and to use Voicemeeter to send the audio over network but that seems like a lot of work.

Much more comfortable than a phone on your head though🙂
